config:
  #time to let the player answer
  timeout: 60
  isbroadcasted: true

messages:
  miss-spell: "&cYou have miss-spelled somethings !"
  no-proposition: "&cThe &8%player% &chasn't sended a proposition"
  accepted: you have accepted the proposition !
  broadcast: "&c %p1% has been married with %p2% !"
  already-married: "&cSorry, but you are already married with someone."
  proposition: Dear %receiver%, \nWould you like to marry me ? \nFrom %sender%. \n\(You have %time% seconds to send your answer !\) \n\(use '/marry accept %player%' to accept the proposition\)
# don't touch under this !!!
partners: #each players have the sames infos !
  player:
    who: none #name of the partner
    propositions:
      otherplayer:
        isblocked: true
        timeout: 60
    home: # coords of the home
      x: 0
      y: 0
      z: 0
      world: world